# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://maven.moxtra.com/repo/moxtra-specs.git'
target 'MoxoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'MEPSDK', '~> 8.10.1'
  # Pods for MoxoDemo

end
